# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
