# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
